# -*- coding: utf-8 -*-
"""skillshare_downloader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i-PqWRHtW_jjrsP38EMjMxSoxgUC9sYA
"""

import urllib.request
import logging
from datetime import datetime
import re
import os

def initialisation():
  logfile=open('lyndalog.log','w')
  logfile.close()
  print('log file created ')

  logging.basicConfig(filename='lyndalog.log',level=logging.DEBUG)

  with open("lyndaurls.txt","a") as file_:
    file_.write("Urls Initisalised at %s\n" %datetime.now())
    logging.info('URLS files Initialized')

initialisation()

def processUrls(chromelog):
  pattern='https.*'
  patternorg='https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)'
  for line in open(chromelog).readlines():
    with open('lyndaurls.txt','a') as file_:
        if(len(re.findall(pattern, line.rstrip()))!=0):
          logging.info("Strriped url is "+re.findall(pattern, line.rstrip())[0])
          file_.write(re.findall(pattern, line.rstrip())[0]+"\n")


processUrls('console.log')

def downloadVideos():
  count=0
  try:
    for line in open('lyndaurls.txt').readlines():
      #print(line)
      if 'mp4' in line:
        count=count+1
        videoname='video'+str(count)+'.mp4'
        print(videoname)
        urllib.request.urlretrieve(line,videoname)
        logging.info('Downloaded  video'+str(count))
        if count==24 :
          break

      else:
        print('False')
  except Exception as e:
    logging.info('Error Occured*******'+e)
    print(e)
    

downloadVideos()

urllib.request.urlretrieve('https://www.linkedin.com/learning/using-python-for-automation/organizing-directories','video3')